---
title       : Class12
subtitle    : Data Processing and Features
author      : Yu-Ru Lin
job         : 
framework   : shower        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
toc         : true
toc_depth   : 2

--- #toc
## Class12
  
* [Set up](#set-up)
* [Big data set](#big)
* [Sparse matrix](#sparse)
* [Feature selection](#featureselection)
* [Frequent patterns](#freq)

--- #set-up .modal 

## Install R packages
```{r, eval=FALSE}
## this tutorial uses the following packages
```

--- .compact #big
## Big data set

* When dealing with big data files, do not read everything into memory.
* We use the sample data from: http://grouplens.org/datasets/hetrec-2011/
* See: http://files.grouplens.org/datasets/hetrec2011/hetrec2011-movielens-readme.txt
  
```{r}
## give the input filename
data.path = 'hetrec2011'
ifilename = sprintf('%s/movies.dat',data.path)
## read the first n=3 lines
lines = readLines(ifilename,n=3)
lines
```

--- .ssscode-nowrap .compact 
## Big data set
```{r, dependson=c(-1)}
## read the first 3 rows into a data.frame object
df = read.csv(ifilename, sep='\t', nrows=3) ## we saw from the first few lines that the field separator is <TAB>
df
```
